### ISSUE TITLE
Feature branch specialisatie

### ISSUE THREAD

**Issue by LucidTaZ** [SagaLhan/tazrum#6]
Ik denk, gezien de hoeveelheid merges, pull requests etc, dat we misschien wat losser kunnen zijn met branch naming.

![screenshot from 2015-01-13 11 23 03](https://cloud.githubusercontent.com/assets/10195108/5719214/b3da0cd2-9b16-11e4-814e-951ec6138782.png)

(Dat zijn allemaal kleine changes.)

Bijv. als ik een branch wil maken met vele diverse dingen, dat ik hem gewoon feature-thijs noem, die misschien in de toekomst nog vaker gaat bestaan.

What say you!?

**Comment by Sylvannes** [comment]
![](http://www.reactiongifs.us/wp-content/uploads/2014/06/agreed_pirates_caribbean.gif)

**Comment by LucidTaZ** [comment]
XD
